{
 "title": "New dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cant Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({kubernetes_namespace_name=~\"$namespace\", kubernetes_pod_name=~\"$pod\", kubernetes_container_name=~\"$container\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Histograma de Logs Infra",
   "type": "timeseries",
   "description": "HIstograma de logs, similar a Observe > Logs en OpenShift Console",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({log_type=\"infrastructure\"} | json [${__interval}]))"
    }
   ]
  },
  {
   "title": "Cant ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({kubernetes_namespace_name=~\"$namespace\", kubernetes_pod_name=~\"$pod\", kubernetes_container_name=~\"$container\"} |= \"error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs Infra",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{log_type=\"infrastructure\", kubernetes_namespace_name=~\"$namespace\", kubernetes_pod_name=~\"$pod\", kubernetes_container_name=~\"$container\"} | json"
    }
   ]
  },
  {
   "title": "Logs ERROR",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{log_type=\"infrastructure\", kubernetes_namespace_name=~\"$namespace\", kubernetes_pod_name=~\"$pod\", kubernetes_container_name=~\"$container\"} \n| json \n| level =~ `(?i)error|crit|fatal`"
    }
   ]
  }
 ]
}