apiVersion: v1
kind: Secret
metadata:
  name: grafana-token-manual
  namespace: openshift-logging
  annotations:
    kubernetes.io/service-account.name: grafana
type: kubernetes.io/service-account-token
